-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_nelos_all.sql
--
-- EVERY NELOS MIGRATION, IN ORDER, IN ONE PASTE.
--
-- Run THIS in the Supabase SQL Editor and ordering stops being something
-- you have to get right. It is the files below concatenated, nothing added
-- and nothing removed:
--
--   1. migration_nelos.sql          cases, comments, categories
--   2. migration_nelos_modules.sql  the linked systems
--   3. migration_nelos_routing.sql  handlers, queues
--   4. migration_nelos_roles.sql    per-category routing rules
--   5. migration_nelos_seats.sql    handler numbers (Admin 1, Auditor 2…)
--   6. migration_nelos_hq.sql       HQ systems that see every case
--   7. migration_nelos_category_system.sql  case titles belong to a system
--   8. migration_nelos_rls.sql      lock the tables down
--   9. migration_nelos_grant.sql    add somebody to Nelos in one step
--
-- Safe to re-run as often as you like: every statement is guarded, later
-- parts stand down where an earlier part has been superseded, and nothing
-- already set up on the User Setting page is overwritten.
--
-- Each part also still works on its own, and refuses with a readable
-- message if run before something it needs.
--
-- KEEPING THIS IN STEP: this file is generated. Edit one of the parts and
-- rebuild it rather than editing here, or the two will drift:
--
--   sh shared/build_nelos_all.sh
--
-- ============================================================================

-- ############################################################################
-- ##  PART 1 of 9 — migration_nelos.sql
-- ############################################################################

-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_nelos.sql
--
-- New module: NELOS — Nursery Carlos (nelos_*)
--
-- Nelos is the one place a case lives. Any module can raise a case; every
-- module shows the ones still pending; the case itself is only ever worked
-- on here. Before Nelos, `operation_follow_up_cases` was the only case-like
-- table and only Batch Detail ever wrote to it — nobody had a list of what
-- was outstanding, so cases were raised and then lost.
--
--   1. nelos_categories     — the kinds of case there are (Planting
--                             Discrepancy, Height Shortfall, Pest, …).
--                             Editable from the module's Settings; nothing
--                             is hard-coded, the same way nops_work_types
--                             works for Nursery Operation.
--   2. nelos_cases          — one row per case. Carries WHERE it came from
--                             (source_module + source_ref, so a case can
--                             link back to the exact page that raised it)
--                             and WHAT it is about (nursery / plot / batch,
--                             all optional — a case need not be about any
--                             of them).
--   3. nelos_case_comments  — the thread on a case. Status changes are
--                             written here too, so the history reads as one
--                             list rather than being split across tables.
--
-- Module access: permissions.modules.nelos = 'admin'|'normal'|'none',
-- granted on the main portal's User Access (JSONB — no DDL needed).
-- What somebody sees once inside is decided by which linked modules and
-- categories they are set up for — see migration_nelos_modules.sql and
-- nelos/nelos_user_setting.html.
--
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- Safe to re-run: every statement is guarded.
-- ============================================================================

-- ────────────────────────────────────────────────────────────────
-- PART 1: Case categories
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_categories (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              TEXT NOT NULL UNIQUE,
  sort_order        INT  NOT NULL DEFAULT 0,
  default_priority  TEXT NOT NULL DEFAULT 'normal',   -- low | normal | high | urgent
  default_days      INT,          -- due date = raised date + this, when set
  active            BOOLEAN NOT NULL DEFAULT true,
  remark            TEXT,
  created_at        TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE nelos_categories ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_categories'
       AND policyname='Authenticated read nelos categories'
  ) THEN
    CREATE POLICY "Authenticated read nelos categories" ON nelos_categories
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_categories'
       AND policyname='Authenticated write nelos categories'
  ) THEN
    CREATE POLICY "Authenticated write nelos categories" ON nelos_categories
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- Seed the case titles we already know about. Matching on the name means a
-- re-run never resurrects one an admin renamed or retired.
--
-- NOT EXISTS rather than ON CONFLICT (name): a later migration scopes a case
-- title to one system and replaces the global unique on name with a
-- per-system one, at which point ON CONFLICT (name) has no constraint to
-- match and a re-run of this file would fail outright.
INSERT INTO nelos_categories (name, sort_order, default_priority, default_days)
SELECT v.name, v.so, v.pri, v.days
  FROM (VALUES
    ('Planting Discrepancy', 10, 'high',   3),
    ('Height Shortfall',     20, 'normal', 7),
    ('Stock Variance',       30, 'high',   3),
    ('Pest / Disease',       40, 'urgent', 1),
    ('Maintenance Overdue',  50, 'normal', 7),
    ('Delivery Issue',       60, 'high',   2),
    ('Other',                90, 'normal', NULL)
  ) AS v(name, so, pri, days)
 WHERE NOT EXISTS (
   SELECT 1 FROM nelos_categories c WHERE lower(c.name) = lower(v.name)
 );

-- ────────────────────────────────────────────────────────────────
-- PART 2: Cases
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_cases (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_no        TEXT UNIQUE,        -- NLS-0001, assigned by trigger below
  title          TEXT NOT NULL,
  description    TEXT,
  category       TEXT,               -- nelos_categories.name, by value not FK
                                     -- so renaming a category never orphans
                                     -- a closed case's history
  priority       TEXT NOT NULL DEFAULT 'normal',  -- low | normal | high | urgent
  status         TEXT NOT NULL DEFAULT 'open',    -- open | in_progress | resolved | closed

  -- Where it came from. source_module is what the To-Do widgets filter on;
  -- source_ref is a link back to the exact page that raised it, written as
  -- seen from a module folder — i.e. starting '../', because the only page
  -- that follows it is nelos/nelos_case.html
  -- (e.g. '../operation/operation_batch_detail.html?batch=264').
  source_module  TEXT NOT NULL DEFAULT 'nelos',   -- operation | audit | scan | nursery_ops | nelos
  source_ref     TEXT,

  -- What it is about. All optional — a case can be about the whole nursery,
  -- one plot, one batch, or nothing physical at all.
  nursery_name   TEXT,
  plot_name      TEXT,
  batch_name     TEXT,

  -- Who owns it. A case is assigned to a person, and that person (or a Nelos
  -- admin) closes it.
  assignee_id    UUID REFERENCES shared_profiles(id) ON DELETE SET NULL,
  assignee_name  TEXT,               -- denormalised so the list renders without
                                     -- reading shared_profiles, which normal
                                     -- users may not select from
  due_date       DATE,

  raised_by      TEXT,
  raised_by_id   UUID REFERENCES shared_profiles(id) ON DELETE SET NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by     TEXT,
  updated_at     TIMESTAMPTZ,

  resolution     TEXT,               -- what was actually done
  resolved_by    TEXT,
  resolved_at    TIMESTAMPTZ,
  closed_by      TEXT,
  closed_at      TIMESTAMPTZ,

  CONSTRAINT nelos_cases_status_chk
    CHECK (status IN ('open','in_progress','resolved','closed')),
  CONSTRAINT nelos_cases_priority_chk
    CHECK (priority IN ('low','normal','high','urgent'))
);

-- The To-Do list is "pending cases, worst first" — this partial index is the
-- one every dashboard widget hits.
CREATE INDEX IF NOT EXISTS nelos_cases_pending_idx
  ON nelos_cases (priority, due_date NULLS LAST, created_at)
  WHERE status IN ('open','in_progress');
CREATE INDEX IF NOT EXISTS nelos_cases_assignee_idx ON nelos_cases (assignee_id, status);
CREATE INDEX IF NOT EXISTS nelos_cases_source_idx   ON nelos_cases (source_module, status);
CREATE INDEX IF NOT EXISTS nelos_cases_plot_idx     ON nelos_cases (plot_name);
CREATE INDEX IF NOT EXISTS nelos_cases_batch_idx    ON nelos_cases (batch_name);

-- Human case number. A sequence rather than count(*)+1 so two people raising
-- a case in the same second cannot land on the same number.
CREATE SEQUENCE IF NOT EXISTS nelos_case_no_seq START 1;

CREATE OR REPLACE FUNCTION public.nelos_assign_case_no()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.case_no IS NULL OR NEW.case_no = '' THEN
    NEW.case_no := 'NLS-' || LPAD(nextval('nelos_case_no_seq')::text, 4, '0');
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS nelos_cases_case_no ON nelos_cases;
CREATE TRIGGER nelos_cases_case_no
  BEFORE INSERT ON nelos_cases
  FOR EACH ROW EXECUTE FUNCTION public.nelos_assign_case_no();

ALTER TABLE nelos_cases ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_cases'
       AND policyname='Authenticated read nelos cases'
  ) THEN
    CREATE POLICY "Authenticated read nelos cases" ON nelos_cases
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_cases'
       AND policyname='Authenticated write nelos cases'
  ) THEN
    CREATE POLICY "Authenticated write nelos cases" ON nelos_cases
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────
-- PART 3: Case comments (and the status-change trail)
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_case_comments (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  case_id      BIGINT NOT NULL REFERENCES nelos_cases(id) ON DELETE CASCADE,
  body         TEXT NOT NULL,
  kind         TEXT NOT NULL DEFAULT 'comment',  -- comment | status | assign
  author_name  TEXT,
  author_id    UUID REFERENCES shared_profiles(id) ON DELETE SET NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS nelos_case_comments_case_idx
  ON nelos_case_comments (case_id, created_at);

ALTER TABLE nelos_case_comments ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_case_comments'
       AND policyname='Authenticated read nelos comments'
  ) THEN
    CREATE POLICY "Authenticated read nelos comments" ON nelos_case_comments
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_case_comments'
       AND policyname='Authenticated write nelos comments'
  ) THEN
    CREATE POLICY "Authenticated write nelos comments" ON nelos_case_comments
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────
-- PART 4: Who a case may be assigned to
--
-- shared_profiles is readable only for your OWN row unless you hold
-- manage_users (see migration_access_and_reviews.sql), so the assignee
-- picker cannot simply select from it. This SECURITY DEFINER function
-- returns the three columns the picker needs and nothing else — the
-- permissions blob stays unreadable. Only people who actually hold Nelos
-- are listed, so a case cannot be assigned to somebody who could never
-- open it.
-- ────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.nelos_assignable_users()
RETURNS TABLE (id UUID, full_name TEXT, email TEXT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p.id, p.full_name, p.email
    FROM public.shared_profiles p
   WHERE COALESCE(p.permissions->'modules'->>'nelos', 'none') <> 'none'
   ORDER BY COALESCE(NULLIF(p.full_name, ''), p.email)
$$;

GRANT EXECUTE ON FUNCTION public.nelos_assignable_users() TO authenticated;

-- ────────────────────────────────────────────────────────────────
-- PART 5: Absorb the old operation_follow_up_cases
--
-- Batch Detail used to insert { batch_name, issue_type, status } and
-- nothing else — there was no UI to read them back. Those rows become
-- Nelos cases so the backlog is visible on day one. The old table is
-- LEFT IN PLACE (not dropped) so this migration stays reversible; nothing
-- writes to it any more once operation_batch_detail.html is deployed.
--
-- Guarded by to_regclass: on a database where the table was never created
-- this whole block is skipped rather than erroring.
-- ────────────────────────────────────────────────────────────────
DO $$
DECLARE
  moved INT := 0;
BEGIN
  IF to_regclass('public.operation_follow_up_cases') IS NULL THEN
    RAISE NOTICE 'operation_follow_up_cases does not exist — nothing to absorb.';
    RETURN;
  END IF;

  INSERT INTO nelos_cases (
    title, description, category, priority, status,
    source_module, source_ref, batch_name, raised_by, created_at
  )
  SELECT
    COALESCE(f.issue_type, 'Follow-up') || ' — batch ' || COALESCE(f.batch_name, '?'),
    'Migrated from operation_follow_up_cases (raised by Batch Detail before Nelos existed).',
    COALESCE(f.issue_type, 'Other'),
    'high',
    -- "Pending Investigation" was the only status the old code ever wrote.
    CASE WHEN f.status ILIKE 'pending%' OR f.status IS NULL THEN 'open' ELSE 'closed' END,
    'operation',
    '../operation/operation_batch_detail.html?batch=' || COALESCE(f.batch_name, ''),
    f.batch_name,
    'system (migrated)',
    -- operation_follow_up_cases was created outside this repo, so its exact
    -- columns are not known here. Reading created_at through to_jsonb means
    -- a table without that column yields NULL instead of failing the whole
    -- migration on an unresolved reference.
    COALESCE((to_jsonb(f)->>'created_at')::timestamptz, now())
  FROM public.operation_follow_up_cases f
  -- Re-runnable: skip anything already brought across.
  WHERE NOT EXISTS (
    SELECT 1 FROM nelos_cases c
     WHERE c.source_module = 'operation'
       AND c.batch_name IS NOT DISTINCT FROM f.batch_name
       AND c.category    IS NOT DISTINCT FROM COALESCE(f.issue_type, 'Other')
       AND c.raised_by   = 'system (migrated)'
  );

  GET DIAGNOSTICS moved = ROW_COUNT;
  RAISE NOTICE 'Absorbed % follow-up case(s) into nelos_cases.', moved;
END $$;

-- ────────────────────────────────────────────────────────────────
-- PART 6: Check it landed
-- ────────────────────────────────────────────────────────────────
SELECT 'nelos_categories'    AS table_name, count(*) AS rows FROM nelos_categories
UNION ALL
SELECT 'nelos_cases',              count(*) FROM nelos_cases
UNION ALL
SELECT 'nelos_cases (pending)',    count(*) FROM nelos_cases WHERE status IN ('open','in_progress')
UNION ALL
SELECT 'nelos_case_comments',      count(*) FROM nelos_case_comments;

-- ── Rollback (manual, if ever needed) ───────────────────────────
--   DROP FUNCTION IF EXISTS public.nelos_assignable_users();
--   DROP TABLE IF EXISTS nelos_case_comments, nelos_cases, nelos_categories;
--   DROP FUNCTION IF EXISTS public.nelos_assign_case_no();
--   DROP SEQUENCE IF EXISTS nelos_case_no_seq;
-- operation_follow_up_cases is untouched by this migration, so reverting
-- Batch Detail's insert target is all that is needed to go back.

-- ############################################################################
-- ##  PART 2 of 9 — migration_nelos_modules.sql
-- ############################################################################

-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_nelos_modules.sql
--
-- NELOS — User Setting: who handles which module's cases.
--
-- Nursery Case Log is linked to several modules. A case raised anywhere
-- lands in that module's block. This migration adds the two tables the
-- User Setting page is built on:
--
--   1. nelos_modules         — the linked modules themselves. A row per
--                              block on the User Setting page. Editable,
--                              so a sixth module is a row rather than a
--                              deploy.
--   2. nelos_module_members  — who handles each module's cases, by email,
--                              and (optionally) which categories they may
--                              see.
--
-- HOW VISIBILITY WORKS — the rule matters, so it is written down once here
-- and implemented once in shared/shared_nelos.js:
--
--   • Nobody has a membership row yet  → they see every case.
--     This is deliberate. Turning the feature on must not blank out the
--     case list for the whole company on day one, and it matches how
--     shared_access.js already treats an unset permission ("a missing key
--     means allowed").
--   • They have at least one membership row → they see cases from those
--     modules only, and within each module only the categories that row
--     allows (an empty/NULL categories array means "all categories in
--     this module").
--   • Nelos admins (permissions.modules.nelos = 'admin') always see
--     everything, whatever their rows say. Without this an admin could
--     lock themselves out of their own case log.
--
-- Requires migration_nelos.sql to have been run first.
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- Safe to re-run: every statement is guarded.
-- ============================================================================

-- ── PREFLIGHT ───────────────────────────────────────────────────
-- Stop with a sentence somebody can act on, rather than letting the first
-- ALTER fail with a bare 'relation does not exist'. Requires: migration_nelos.sql.
DO $preflight$
BEGIN
  IF to_regclass('public.nelos_cases') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos migrations are out of order: "nelos_cases" does not exist yet.',
      HINT    = 'Run migration_nelos.sql first. The full order is: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql, migration_nelos_roles.sql, migration_nelos_seats.sql — or just run migration_nelos_all.sql, which is all five in one paste.';
  END IF;
END $preflight$;


-- ────────────────────────────────────────────────────────────────
-- PART 1: The linked modules
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_modules (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key         TEXT NOT NULL UNIQUE,   -- matches nelos_cases.source_module
  label       TEXT NOT NULL,          -- what the block is called on screen
  icon        TEXT,
  href        TEXT,                   -- where the module lives, from /nelos/
  sort_order  INT  NOT NULL DEFAULT 0,
  active      BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE nelos_modules ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_modules'
       AND policyname='Authenticated read nelos modules'
  ) THEN
    CREATE POLICY "Authenticated read nelos modules" ON nelos_modules
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_modules'
       AND policyname='Authenticated write nelos modules'
  ) THEN
    CREATE POLICY "Authenticated write nelos modules" ON nelos_modules
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- The five modules the case log is linked to today.
--
-- `key` is the value written into nelos_cases.source_module, so these must
-- match the module keys the rest of the portal already uses:
--   operation   — Nursery Seedling Stock Management ("AI Stock System")
--   nursery_ops — Nursery Operation Management
--   scan        — the FC Portal (scan.mjmnursery.com)
--   mobile      — the Mobile app ("Admin Portal")
--   audit       — Nursery Audit ("Auditor Portal")
--
-- ON CONFLICT DO NOTHING so a re-run never undoes a label somebody edited.
INSERT INTO nelos_modules (key, label, icon, href, sort_order) VALUES
  ('operation',   'AI Stock System',    '🌱', '../operation/operation_dashboard.html',     10),
  ('nursery_ops', 'Nursery Operation',  '🌿', '../nursery_ops/nursery_ops_dashboard.html', 20),
  ('scan',        'FC Portal',          '📱', 'https://scan.mjmnursery.com',               30),
  ('mobile',      'Admin Portal',       '🗂️', '../mobile/mobile_landing.html',             40),
  ('audit',       'Auditor Portal',     '📋', '../audit/audit_home.html',                  50)
ON CONFLICT (key) DO NOTHING;

-- Label corrections, applied only where the row still carries the label this
-- file originally seeded. A label somebody has since edited on the User
-- Setting page is left alone — this fixes the default, it does not stomp a
-- decision.
UPDATE nelos_modules SET label = 'Seedling Stock System'
 WHERE key = 'operation' AND label = 'AI Stock System';
UPDATE nelos_modules SET label = 'Audit Portal'
 WHERE key = 'audit'     AND label = 'Auditor Portal';

-- ── Renaming a module KEY (read before you try it) ──────────────
-- `label` is display only — rename it freely, on this page or here.
-- `key` is an identifier, and three other things carry a copy of it:
--
--   1. nelos_cases.source_module   — every case already filed
--   2. nelos_module_members.module_key — handled by ON UPDATE CASCADE below
--   3. four hardcoded call sites that raise or filter cases:
--        operation/operation_batch_detail.html   source: 'operation'
--        operation/operation_dashboard.html      source: 'operation'
--        nursery_ops/nursery_ops_dashboard.html  source: 'nursery_ops'
--        audit/audit_admin.html                  source: 'audit'
--      plus the SOURCE_LABEL fallback map in shared/shared_nelos.js
--
-- So a key rename is a code change AND a data change, and doing only one
-- of them silently orphans cases: they keep the old source_module, stop
-- matching any block, and vanish from the To-Do lists. To rename a key,
-- change the call sites first, then run BOTH statements together:
--
--   UPDATE nelos_modules SET key = 'new_key' WHERE key = 'old_key';
--   UPDATE nelos_cases SET source_module = 'new_key' WHERE source_module = 'old_key';
--
-- The member rows follow on their own.
--
-- The keys shipped here deliberately match the table prefixes the rest of
-- the portal already uses (operation_, nops_, audit_…), which is what the
-- grey chip under each block name is showing.

-- (The constraint that makes a key rename carry its member rows is set up
--  in PART 2, once nelos_module_members exists.)

-- ────────────────────────────────────────────────────────────────
-- PART 2: Who handles each module's cases
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_module_members (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_key  TEXT NOT NULL REFERENCES nelos_modules(key) ON DELETE CASCADE,

  -- Email is the handle, because that is what an admin types and because a
  -- person can be added before they have ever signed in. user_id is filled
  -- in when the email matches a shared_profiles row, and is what the app
  -- actually matches on once it is known.
  email       TEXT NOT NULL,
  user_id     UUID REFERENCES shared_profiles(id) ON DELETE CASCADE,
  full_name   TEXT,

  -- Which case categories this person may see in this module.
  -- NULL or empty = every category. Values are nelos_categories.name.
  categories  TEXT[],

  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by  TEXT
);

-- One row per person per module. Case-insensitive, so adding
-- "Ali@mjm.com" twice in different case cannot make two rows.
CREATE UNIQUE INDEX IF NOT EXISTS nelos_module_members_uniq
  ON nelos_module_members (module_key, lower(email));
CREATE INDEX IF NOT EXISTS nelos_module_members_user_idx
  ON nelos_module_members (user_id);
CREATE INDEX IF NOT EXISTS nelos_module_members_email_idx
  ON nelos_module_members (lower(email));

-- Let a key rename carry its member rows with it, instead of failing on the
-- foreign key. The table above may have been created by an earlier run of
-- this file, when the constraint was still ON DELETE only, so this upgrades
-- it in place. Guarded on confupdtype so re-running does not churn it.
DO $$
DECLARE c TEXT;
BEGIN
  SELECT conname INTO c
    FROM pg_constraint
   WHERE conrelid  = 'public.nelos_module_members'::regclass
     AND contype   = 'f'
     AND confrelid = 'public.nelos_modules'::regclass
     AND confupdtype <> 'c';          -- 'c' = already ON UPDATE CASCADE
  IF c IS NOT NULL THEN
    EXECUTE format('ALTER TABLE nelos_module_members DROP CONSTRAINT %I', c);
    ALTER TABLE nelos_module_members
      ADD CONSTRAINT nelos_module_members_module_key_fkey
      FOREIGN KEY (module_key) REFERENCES nelos_modules(key)
      ON UPDATE CASCADE ON DELETE CASCADE;
    RAISE NOTICE 'nelos_module_members.module_key now cascades on rename.';
  END IF;
END $$;

ALTER TABLE nelos_module_members ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_module_members'
       AND policyname='Authenticated read nelos members'
  ) THEN
    CREATE POLICY "Authenticated read nelos members" ON nelos_module_members
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_module_members'
       AND policyname='Authenticated write nelos members'
  ) THEN
    CREATE POLICY "Authenticated write nelos members" ON nelos_module_members
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────
-- PART 3: Looking somebody up by email
--
-- The User Setting page takes a typed email and needs the matching profile
-- so the member row can carry a user_id and a real name. shared_profiles
-- is readable only for your own row unless you hold manage_users, so this
-- goes through a SECURITY DEFINER function that returns three columns and
-- nothing else — the permissions blob stays unreadable.
-- ────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.nelos_lookup_user(p_email TEXT)
RETURNS TABLE (id UUID, full_name TEXT, email TEXT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p.id, p.full_name, p.email
    FROM public.shared_profiles p
   WHERE lower(p.email) = lower(trim(p_email))
   LIMIT 1
$$;

GRANT EXECUTE ON FUNCTION public.nelos_lookup_user(TEXT) TO authenticated;

-- Everybody in the system, for the "add someone" dropdown on the User
-- Setting page — so an admin picks a colleague instead of typing an address
-- from memory and mistyping it.
--
-- SECURITY DEFINER reads past the shared_profiles policy, so this checks
-- for itself who is asking and returns NOTHING to anybody who is not a
-- Nelos admin or a portal user-manager. That is the same test the User
-- Setting page gates on, so the function cannot become a way for an
-- ordinary account to enumerate everyone's email address.
CREATE OR REPLACE FUNCTION public.nelos_directory()
RETURNS TABLE (id UUID, full_name TEXT, email TEXT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p.id, p.full_name, p.email
    FROM public.shared_profiles p
   WHERE p.email IS NOT NULL
     AND p.email <> ''
     AND EXISTS (
       SELECT 1 FROM public.shared_profiles me
        WHERE me.id = auth.uid()
          AND (COALESCE((me.permissions->>'manage_users')::boolean, false)
               OR COALESCE(me.permissions->'modules'->>'nelos', 'none') = 'admin')
     )
   ORDER BY COALESCE(NULLIF(p.full_name, ''), p.email)
$$;

GRANT EXECUTE ON FUNCTION public.nelos_directory() TO authenticated;

-- Back-fill user_id on any member row added before that person signed up.
-- Cheap, and it means an admin never has to re-add somebody.
UPDATE nelos_module_members m
   SET user_id   = p.id,
       full_name = COALESCE(m.full_name, p.full_name)
  FROM public.shared_profiles p
 WHERE m.user_id IS NULL
   AND lower(p.email) = lower(m.email);

-- ────────────────────────────────────────────────────────────────
-- PART 4: Check it landed
-- ────────────────────────────────────────────────────────────────
SELECT m.key, m.label, count(mm.id) AS members
  FROM nelos_modules m
  LEFT JOIN nelos_module_members mm ON mm.module_key = m.key
 GROUP BY m.key, m.label, m.sort_order
 ORDER BY m.sort_order;

-- ── Rollback (manual, if ever needed) ───────────────────────────
--   DROP FUNCTION IF EXISTS public.nelos_lookup_user(TEXT);
--   DROP TABLE IF EXISTS nelos_module_members, nelos_modules;

-- ############################################################################
-- ##  PART 3 of 9 — migration_nelos_routing.sql
-- ############################################################################

-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_nelos_routing.sql
--
-- NELOS — handlers and case routing.
--
-- WHY THIS REPLACES THE MEMBERSHIP MODEL
--
-- The first cut said "this person belongs to these module blocks", and an
-- admin added people to a block by email. That was wrong in practice: an
-- auditor needs the To-Do list on the Audit Portal AND on the Seedling
-- Stock system AND on the Admin Portal. Membership-per-module made that a
-- list of three rows to maintain, and it still could not say the important
-- thing — which queue that person actually works.
--
-- The model now has two halves:
--
--   1. A HANDLER is a person with one home module — "this person handles
--      Nursery Operation cases". Nothing is added by hand: anybody granted
--      Nelos on the main portal's User Access appears in the list ready to
--      be pinned.
--
--   2. ROUTING says where a case goes when it is raised. A case raised in
--      the Audit Portal is worked by the Nursery Operation handlers; one
--      raised on the FC Portal is worked by Audit. That is a property of
--      the section, not of the person, so it lives on nelos_modules.
--
-- WHAT SOMEBODY SEES, ONCE PINNED
--   • every case sitting in their home module's queue, wherever they are
--     in the system, and
--   • every case assigned to them personally, whatever queue it is in.
-- So an auditor pinned to Audit still gets the To-Do dock on the Stock
-- system — showing Audit's queue plus anything with their name on it.
--
-- Not yet pinned → sees everything, as before. A person who has just been
-- granted Nelos must not find an empty screen.
-- A Nelos admin → sees everything regardless.
--
-- Requires migration_nelos.sql and migration_nelos_modules.sql.
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- Safe to re-run: every statement is guarded.
-- ============================================================================

-- ── PREFLIGHT ───────────────────────────────────────────────────
-- Stop with a sentence somebody can act on, rather than letting the first
-- ALTER fail with a bare 'relation does not exist'. Requires: migration_nelos.sql then migration_nelos_modules.sql.
DO $preflight$
BEGIN
  IF to_regclass('public.nelos_cases') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos migrations are out of order: "nelos_cases" does not exist yet.',
      HINT    = 'Run migration_nelos.sql first. The full order is: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql, migration_nelos_roles.sql, migration_nelos_seats.sql — or just run migration_nelos_all.sql, which is all five in one paste.';
  END IF;
  IF to_regclass('public.nelos_modules') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos migrations are out of order: "nelos_modules" does not exist yet.',
      HINT    = 'Run migration_nelos_modules.sql first. The full order is: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql, migration_nelos_roles.sql, migration_nelos_seats.sql — or just run migration_nelos_all.sql, which is all five in one paste.';
  END IF;
END $preflight$;


-- ────────────────────────────────────────────────────────────────
-- PART 1: Sections gain "may raise" and "routes to"
-- ────────────────────────────────────────────────────────────────
ALTER TABLE nelos_modules ADD COLUMN IF NOT EXISTS can_create BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE nelos_modules ADD COLUMN IF NOT EXISTS route_to   TEXT;

-- route_to names another section, whose handlers work the case. NULL means
-- "handled where it was raised". ON UPDATE CASCADE so renaming a key does
-- not silently break the routing table.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'public.nelos_modules'::regclass
       AND conname  = 'nelos_modules_route_to_fkey'
  ) THEN
    ALTER TABLE nelos_modules
      ADD CONSTRAINT nelos_modules_route_to_fkey
      FOREIGN KEY (route_to) REFERENCES nelos_modules(key)
      ON UPDATE CASCADE ON DELETE SET NULL;
  END IF;
END $$;

-- The two routes described when this was specified. Applied only where no
-- route has been set yet, so a re-run never overrides the page.
UPDATE nelos_modules SET route_to = 'nursery_ops'
 WHERE key = 'audit' AND route_to IS NULL;
UPDATE nelos_modules SET route_to = 'audit'
 WHERE key = 'scan'  AND route_to IS NULL;

-- ────────────────────────────────────────────────────────────────
-- PART 2: A case carries the queue it is waiting in
--
-- source_module says where a case CAME FROM and never changes.
-- assigned_module says who is WORKING it, and is what every To-Do list
-- filters on. Keeping them apart is the whole point: an FC Portal case
-- worked by Audit has to still read as an FC Portal case.
-- ────────────────────────────────────────────────────────────────
ALTER TABLE nelos_cases ADD COLUMN IF NOT EXISTS assigned_module TEXT;

CREATE INDEX IF NOT EXISTS nelos_cases_queue_idx
  ON nelos_cases (assigned_module, status);

-- Existing cases are worked where they were raised until routing says
-- otherwise. Only fills blanks, so re-running cannot move a case.
UPDATE nelos_cases SET assigned_module = source_module
 WHERE assigned_module IS NULL;

-- Route on insert, so it does not matter which page raised the case or
-- whether that page remembered to work the routing out.
-- ── Superseded by migration_nelos_roles.sql ─────────────────────
-- That file redefines this trigger to be category-aware and widens both
-- scope functions with a role column. Postgres will not let CREATE OR
-- REPLACE change a function's return type, so re-running THIS file after
-- that one used to fail outright — and, had it succeeded, would have
-- quietly reverted the newer behaviour. So when nelos_roles exists, the
-- later migration owns these three objects and this block stands down.
DO $guard$
BEGIN
IF to_regclass('public.nelos_roles') IS NOT NULL THEN
  RAISE NOTICE 'nelos_roles present — migration_nelos_roles.sql owns the routing trigger and scope functions; leaving them as they are.';
  RETURN;
END IF;

EXECUTE $fn$
CREATE OR REPLACE FUNCTION public.nelos_route_case()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE dest TEXT;
BEGIN
  -- An explicit assigned_module wins: routing is the default, not a rule.
  IF NEW.assigned_module IS NOT NULL AND NEW.assigned_module <> '' THEN
    RETURN NEW;
  END IF;
  SELECT route_to INTO dest FROM nelos_modules WHERE key = NEW.source_module;
  NEW.assigned_module := COALESCE(dest, NEW.source_module);
  RETURN NEW;
END $$
$fn$;

EXECUTE $fn$
DROP TRIGGER IF EXISTS nelos_cases_route ON nelos_cases;
CREATE TRIGGER nelos_cases_route
  BEFORE INSERT ON nelos_cases
  FOR EACH ROW EXECUTE FUNCTION public.nelos_route_case();

-- ────────────────────────────────────────────────────────────────
-- PART 3: Handlers
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_handlers (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         UUID NOT NULL UNIQUE REFERENCES shared_profiles(id) ON DELETE CASCADE,
  email           TEXT,
  full_name       TEXT,

  -- The pin: which module's cases this person handles. NULL = not pinned
  -- yet, which means unrestricted rather than blocked.
  primary_module  TEXT REFERENCES nelos_modules(key) ON UPDATE CASCADE ON DELETE SET NULL,

  -- Optional narrowing inside that queue. NULL/empty = every category.
  categories      TEXT[],

  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by      TEXT
);

CREATE INDEX IF NOT EXISTS nelos_handlers_module_idx ON nelos_handlers (primary_module);

ALTER TABLE nelos_handlers ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_handlers'
       AND policyname='Authenticated read nelos handlers'
  ) THEN
    CREATE POLICY "Authenticated read nelos handlers" ON nelos_handlers
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
     WHERE schemaname='public' AND tablename='nelos_handlers'
       AND policyname='Authenticated write nelos handlers'
  ) THEN
    CREATE POLICY "Authenticated write nelos handlers" ON nelos_handlers
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- Carry the old membership rows across. Somebody who was on several blocks
-- gets the lowest-sorted one as their home module — a guess, but a visible
-- one an admin can correct on the page, and better than dropping the work
-- that went into setting them up.
DO $$
DECLARE moved INT := 0;
BEGIN
  IF to_regclass('public.nelos_module_members') IS NULL THEN RETURN; END IF;

  INSERT INTO nelos_handlers (user_id, email, full_name, primary_module, categories, updated_by)
  SELECT DISTINCT ON (mm.user_id)
         mm.user_id, mm.email, mm.full_name, mm.module_key, mm.categories,
         'system (migrated from module members)'
    FROM public.nelos_module_members mm
    JOIN public.nelos_modules m ON m.key = mm.module_key
   WHERE mm.user_id IS NOT NULL
   ORDER BY mm.user_id, m.sort_order, mm.created_at
  ON CONFLICT (user_id) DO NOTHING;

  GET DIAGNOSTICS moved = ROW_COUNT;
  RAISE NOTICE 'Carried % handler(s) across from nelos_module_members.', moved;
END $$;

-- nelos_module_members is left in place, unread, so this stays reversible.

-- ────────────────────────────────────────────────────────────────
-- PART 4: The people list
--
-- Everyone the main portal has granted Nelos to, with their handler row
-- if they have one. This is what the User Setting page lists — no adding
-- by hand, because the portal already decided who is in.
--
-- SECURITY DEFINER to read past the shared_profiles policy, so it checks
-- for itself who is asking and answers nobody but a Nelos admin or a
-- portal user-manager.
-- ────────────────────────────────────────────────────────────────
$fn$;

EXECUTE $fn$
CREATE OR REPLACE FUNCTION public.nelos_people()
RETURNS TABLE (
  id             UUID,
  full_name      TEXT,
  email          TEXT,
  nelos_level    TEXT,
  primary_module TEXT,
  categories     TEXT[]
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p.id,
         p.full_name,
         p.email,
         COALESCE(p.permissions->'modules'->>'nelos', 'none') AS nelos_level,
         h.primary_module,
         h.categories
    FROM public.shared_profiles p
    LEFT JOIN public.nelos_handlers h ON h.user_id = p.id
   WHERE COALESCE(p.permissions->'modules'->>'nelos', 'none') <> 'none'
     AND EXISTS (
       SELECT 1 FROM public.shared_profiles me
        WHERE me.id = auth.uid()
          AND (COALESCE((me.permissions->>'manage_users')::boolean, false)
               OR COALESCE(me.permissions->'modules'->>'nelos', 'none') = 'admin')
     )
   ORDER BY COALESCE(NULLIF(p.full_name, ''), p.email)
$$
$fn$;

EXECUTE $fn$
GRANT EXECUTE ON FUNCTION public.nelos_people() TO authenticated;

-- My own pin, readable by me alone — this is what the To-Do lists ask for
-- on every page, and it must work for an ordinary user, not just an admin.
$fn$;

EXECUTE $fn$
CREATE OR REPLACE FUNCTION public.nelos_my_scope()
RETURNS TABLE (primary_module TEXT, categories TEXT[], is_admin BOOLEAN)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT h.primary_module,
         h.categories,
         COALESCE(p.permissions->'modules'->>'nelos', 'none') = 'admin'
    FROM public.shared_profiles p
    LEFT JOIN public.nelos_handlers h ON h.user_id = p.id
   WHERE p.id = auth.uid()
$$
$fn$;

EXECUTE $fn$
GRANT EXECUTE ON FUNCTION public.nelos_my_scope() TO authenticated
$fn$;
END $guard$;

-- ────────────────────────────────────────────────────────────────
-- PART 5: Check it landed
-- ────────────────────────────────────────────────────────────────
SELECT m.key,
       m.label,
       m.can_create,
       COALESCE(m.route_to, m.key || ' (itself)') AS worked_by,
       (SELECT count(*) FROM nelos_handlers h WHERE h.primary_module = m.key) AS handlers,
       (SELECT count(*) FROM nelos_cases c
         WHERE c.assigned_module = m.key AND c.status IN ('open','in_progress')) AS pending
  FROM nelos_modules m
 ORDER BY m.sort_order;

-- ── Rollback (manual, if ever needed) ───────────────────────────
--   DROP TRIGGER IF EXISTS nelos_cases_route ON nelos_cases;
--   DROP FUNCTION IF EXISTS public.nelos_route_case();
--   DROP FUNCTION IF EXISTS public.nelos_people();
--   DROP FUNCTION IF EXISTS public.nelos_my_scope();
--   DROP TABLE IF EXISTS nelos_handlers;
--   ALTER TABLE nelos_cases   DROP COLUMN IF EXISTS assigned_module;
--   ALTER TABLE nelos_modules DROP COLUMN IF EXISTS can_create, DROP COLUMN IF EXISTS route_to;
-- nelos_module_members is untouched, so the old page would work again.

-- ############################################################################
-- ##  PART 4 of 9 — migration_nelos_roles.sql
-- ############################################################################

-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_nelos_roles.sql
--
-- NELOS — roles inside a system, and routing per category.
--
-- Two things the section-level routing could not say:
--
--   1. "A Planting Discrepancy from the Stock system goes to Nursery
--      Operation, but a Stock Variance from the same system stays with
--      Stock." Routing was one rule per section; it is now one rule per
--      (section, category), with a section default underneath.
--
--   2. "The Admin Portal has two people. Some cases go to Admin 1, some to
--      Admin 2." A queue could only be a whole module, so there was no way
--      to name a seat inside it. A ROLE is that seat: handlers are pinned
--      to a system AND a role in it, and a routing rule may target the
--      role rather than the whole module.
--
-- HOW A NEW CASE IS ROUTED — first match wins:
--      1. a rule for exactly this (source_module, category)
--      2. the section's default rule (category IS NULL)
--      3. the section itself
--   An assigned_module set by the caller always wins over all three:
--   routing is the default, not a rule.
--
-- WHAT SOMEBODY SEES — unchanged except for the role step:
--      • their home module's queue, EXCEPT cases routed to a role that is
--        not theirs. A case with no role is the whole module's to take.
--      • plus anything assigned to them personally, in any queue, past
--        every filter.
--      • unpinned, or Nelos admin → everything.
--
-- nelos_modules.route_to is SUPERSEDED by nelos_routes and is migrated into
-- it as each section's default rule. The column is left in place so this
-- stays reversible, but nothing reads it any more — see PART 4.
--
-- Requires migration_nelos.sql, migration_nelos_modules.sql and
-- migration_nelos_routing.sql.
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- Safe to re-run: every statement is guarded.
-- ============================================================================

-- ── PREFLIGHT ───────────────────────────────────────────────────
-- Stop with a sentence somebody can act on, rather than letting the first
-- ALTER fail with a bare 'relation does not exist'. Requires: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql.
DO $preflight$
BEGIN
  IF to_regclass('public.nelos_cases') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos migrations are out of order: "nelos_cases" does not exist yet.',
      HINT    = 'Run migration_nelos.sql first. The full order is: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql, migration_nelos_roles.sql, migration_nelos_seats.sql — or just run migration_nelos_all.sql, which is all five in one paste.';
  END IF;
  IF to_regclass('public.nelos_modules') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos migrations are out of order: "nelos_modules" does not exist yet.',
      HINT    = 'Run migration_nelos_modules.sql first. The full order is: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql, migration_nelos_roles.sql, migration_nelos_seats.sql — or just run migration_nelos_all.sql, which is all five in one paste.';
  END IF;
  IF to_regclass('public.nelos_handlers') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos migrations are out of order: "nelos_handlers" does not exist yet.',
      HINT    = 'Run migration_nelos_routing.sql first. The full order is: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql, migration_nelos_roles.sql, migration_nelos_seats.sql — or just run migration_nelos_all.sql, which is all five in one paste.';
  END IF;
END $preflight$;


-- ────────────────────────────────────────────────────────────────
-- PART 1: Roles — the seats inside a system
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_roles (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_key  TEXT NOT NULL REFERENCES nelos_modules(key) ON UPDATE CASCADE ON DELETE CASCADE,
  name        TEXT NOT NULL,          -- 'Admin 1', 'Senior Auditor', …
  sort_order  INT  NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT nelos_roles_name_not_blank CHECK (btrim(name) <> '')
);

-- Two seats with the same name in one system would be indistinguishable on
-- every screen, so they are refused. Case-insensitive: "Admin 1" and
-- "admin 1" are the same seat.
CREATE UNIQUE INDEX IF NOT EXISTS nelos_roles_uniq
  ON nelos_roles (module_key, lower(name));

ALTER TABLE nelos_roles ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='nelos_roles'
       AND policyname='Authenticated read nelos roles') THEN
    CREATE POLICY "Authenticated read nelos roles" ON nelos_roles
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='nelos_roles'
       AND policyname='Authenticated write nelos roles') THEN
    CREATE POLICY "Authenticated write nelos roles" ON nelos_roles
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- No roles are seeded. A seat is a decision about how a team is organised,
-- and inventing "Admin 1"/"Admin 2" here would put words in the admin's
-- mouth. Until roles exist, every rule targets a whole module, which is
-- exactly how routing behaved before this migration.

-- ────────────────────────────────────────────────────────────────
-- PART 2: A handler sits in a system AND a seat
-- ────────────────────────────────────────────────────────────────
ALTER TABLE nelos_handlers
  ADD COLUMN IF NOT EXISTS role_id BIGINT REFERENCES nelos_roles(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS nelos_handlers_role_idx ON nelos_handlers (role_id);

-- A role belongs to one module, so a handler's seat must be in the system
-- they are pinned to. Enforced in the app (the picker only offers that
-- module's roles); this cleans up anything left behind when somebody is
-- moved to a different system.
UPDATE nelos_handlers h
   SET role_id = NULL
  FROM nelos_roles r
 WHERE h.role_id = r.id
   AND h.primary_module IS DISTINCT FROM r.module_key;

-- ────────────────────────────────────────────────────────────────
-- PART 3: Routing rules, per section and category
-- ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS nelos_routes (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_module  TEXT NOT NULL REFERENCES nelos_modules(key) ON UPDATE CASCADE ON DELETE CASCADE,

  -- NULL = this section's default, used by any category without its own
  -- rule. Stored by name, like nelos_cases.category, so renaming a
  -- category in Settings never orphans a rule silently.
  category       TEXT,

  to_module      TEXT NOT NULL REFERENCES nelos_modules(key) ON UPDATE CASCADE ON DELETE CASCADE,
  to_role_id     BIGINT REFERENCES nelos_roles(id) ON DELETE SET NULL,

  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by     TEXT
);

-- One rule per category per section, and one default per section. Two
-- partial indexes rather than a plain UNIQUE, because Postgres treats NULLs
-- as distinct and would happily allow a second default row.
CREATE UNIQUE INDEX IF NOT EXISTS nelos_routes_cat_uniq
  ON nelos_routes (source_module, category) WHERE category IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS nelos_routes_default_uniq
  ON nelos_routes (source_module) WHERE category IS NULL;

ALTER TABLE nelos_routes ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='nelos_routes'
       AND policyname='Authenticated read nelos routes') THEN
    CREATE POLICY "Authenticated read nelos routes" ON nelos_routes
      FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='nelos_routes'
       AND policyname='Authenticated write nelos routes') THEN
    CREATE POLICY "Authenticated write nelos routes" ON nelos_routes
      FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ────────────────────────────────────────────────────────────────
-- PART 4: Carry the old section-level routes across
--
-- Every section that had a route_to becomes a default rule here. Only
-- inserted where no default exists yet, so a re-run cannot undo an edit
-- made on the User Setting page.
-- ────────────────────────────────────────────────────────────────
INSERT INTO nelos_routes (source_module, category, to_module, updated_by)
SELECT m.key, NULL, m.route_to, 'system (migrated from nelos_modules.route_to)'
  FROM nelos_modules m
 WHERE m.route_to IS NOT NULL
   AND NOT EXISTS (
     SELECT 1 FROM nelos_routes r
      WHERE r.source_module = m.key AND r.category IS NULL
   );

-- ────────────────────────────────────────────────────────────────
-- PART 5: A case remembers which seat it was sent to
-- ────────────────────────────────────────────────────────────────
ALTER TABLE nelos_cases
  ADD COLUMN IF NOT EXISTS assigned_role_id BIGINT REFERENCES nelos_roles(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS nelos_cases_role_idx ON nelos_cases (assigned_role_id);

-- Routing, now category-aware. Replaces the version in
-- migration_nelos_routing.sql; that file's trigger is redefined here rather
-- than duplicated, so running the migrations in order leaves one rule.
-- ── Superseded by migration_nelos_seats.sql ─────────────────────
-- That file replaces named roles with a number inside each system, and
-- redefines this trigger and both scope functions to match. Re-running
-- THIS file afterwards would drop the newer functions and put the
-- role-shaped ones back, silently reverting the change — so when
-- nelos_handlers.seat_no exists, the later migration owns these objects
-- and this block stands down.
DO $guard$
BEGIN
IF EXISTS (SELECT 1 FROM information_schema.columns
            WHERE table_schema='public' AND table_name='nelos_handlers'
              AND column_name='seat_no') THEN
  RAISE NOTICE 'nelos_handlers.seat_no present — migration_nelos_seats.sql owns the routing trigger and scope functions; leaving them as they are.';
  RETURN;
END IF;

EXECUTE $fn$
CREATE OR REPLACE FUNCTION public.nelos_route_case()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE r RECORD;
BEGIN
  -- An explicit destination wins: routing is the default, not a rule.
  IF NEW.assigned_module IS NOT NULL AND NEW.assigned_module <> '' THEN
    RETURN NEW;
  END IF;

  -- Exact category rule first, then the section default. ORDER BY puts the
  -- category rule ahead of the default, so one query settles it.
  SELECT nr.to_module, nr.to_role_id INTO r
    FROM nelos_routes nr
   WHERE nr.source_module = NEW.source_module
     AND (nr.category = NEW.category OR nr.category IS NULL)
   ORDER BY (nr.category IS NULL)          -- false (0) sorts before true (1)
   LIMIT 1;

  IF FOUND THEN
    NEW.assigned_module  := r.to_module;
    -- Only carry the seat when the caller has not named one already.
    IF NEW.assigned_role_id IS NULL THEN
      NEW.assigned_role_id := r.to_role_id;
    END IF;
  ELSE
    NEW.assigned_module := NEW.source_module;
  END IF;

  RETURN NEW;
END $$
$fn$;

EXECUTE $fn$
DROP TRIGGER IF EXISTS nelos_cases_route ON nelos_cases;
CREATE TRIGGER nelos_cases_route
  BEFORE INSERT ON nelos_cases
  FOR EACH ROW EXECUTE FUNCTION public.nelos_route_case()
$fn$;

EXECUTE $fn$
DROP FUNCTION IF EXISTS public.nelos_my_scope()
$fn$;

EXECUTE $fn$
DROP FUNCTION IF EXISTS public.nelos_people()
$fn$;

EXECUTE $fn$
CREATE FUNCTION public.nelos_my_scope()
RETURNS TABLE (primary_module TEXT, role_id BIGINT, categories TEXT[], is_admin BOOLEAN)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT h.primary_module,
         h.role_id,
         h.categories,
         COALESCE(p.permissions->'modules'->>'nelos', 'none') = 'admin'
    FROM public.shared_profiles p
    LEFT JOIN public.nelos_handlers h ON h.user_id = p.id
   WHERE p.id = auth.uid()
$$
$fn$;

EXECUTE $fn$
GRANT EXECUTE ON FUNCTION public.nelos_my_scope() TO authenticated
$fn$;

EXECUTE $fn$
CREATE FUNCTION public.nelos_people()
RETURNS TABLE (
  id             UUID,
  full_name      TEXT,
  email          TEXT,
  nelos_level    TEXT,
  primary_module TEXT,
  role_id        BIGINT,
  categories     TEXT[]
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p.id,
         p.full_name,
         p.email,
         COALESCE(p.permissions->'modules'->>'nelos', 'none') AS nelos_level,
         h.primary_module,
         h.role_id,
         h.categories
    FROM public.shared_profiles p
    LEFT JOIN public.nelos_handlers h ON h.user_id = p.id
   WHERE COALESCE(p.permissions->'modules'->>'nelos', 'none') <> 'none'
     AND EXISTS (
       SELECT 1 FROM public.shared_profiles me
        WHERE me.id = auth.uid()
          AND (COALESCE((me.permissions->>'manage_users')::boolean, false)
               OR COALESCE(me.permissions->'modules'->>'nelos', 'none') = 'admin')
     )
   ORDER BY COALESCE(NULLIF(p.full_name, ''), p.email)
$$
$fn$;

EXECUTE $fn$
GRANT EXECUTE ON FUNCTION public.nelos_people() TO authenticated
$fn$;
END $guard$;

-- ────────────────────────────────────────────────────────────────
-- PART 7: Check it landed
-- ────────────────────────────────────────────────────────────────
SELECT r.source_module AS raised_in,
       COALESCE(r.category, '(any other category)') AS for_category,
       r.to_module AS worked_by,
       COALESCE(ro.name, '(anyone in that module)') AS seat
  FROM nelos_routes r
  LEFT JOIN nelos_roles ro ON ro.id = r.to_role_id
  JOIN nelos_modules m ON m.key = r.source_module
 ORDER BY m.sort_order, (r.category IS NULL) DESC, r.category;

-- ── Rollback (manual, if ever needed) ───────────────────────────
--   ALTER TABLE nelos_cases    DROP COLUMN IF EXISTS assigned_role_id;
--   ALTER TABLE nelos_handlers DROP COLUMN IF EXISTS role_id;
--   DROP TABLE IF EXISTS nelos_routes, nelos_roles;
--   then re-run migration_nelos_routing.sql to restore its trigger and
--   the two-column nelos_my_scope()/nelos_people(). nelos_modules.route_to
--   was never cleared, so the old section routing comes back with it.

-- ############################################################################
-- ##  PART 5 of 9 — migration_nelos_seats.sql
-- ############################################################################

-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_nelos_seats.sql
--
-- NELOS — one list of handlers, numbered inside their system.
--
-- WHY THIS REPLACES nelos_roles
--
-- The previous cut made "seats" a thing you had to invent and name before
-- anybody could hold one: a Roles tab, then a Handlers tab, then a pin on
-- each. Two screens and a made-up word for something much simpler.
--
-- A handler's role is just WHICH SYSTEM they answer for and WHICH NUMBER
-- they are in it. Pin somebody to the Admin Portal and they are Admin 1;
-- pin the next person and they are Admin 2. Nothing to name, one list,
-- and the routing page can then say "this category goes to Admin 2".
--
-- So:
--   • nelos_modules.handler_label — what one person in this system is
--     called, singular. 'Admin' for the Admin Portal, 'Auditor' for the
--     Audit Portal. Combined with the number this is the whole role name.
--   • nelos_handlers.seat_no      — their position in that system, 1, 2, 3…
--   • nelos_routes.to_seat_no     — a rule may target a number, or leave it
--     blank for anyone in the system.
--   • nelos_cases.assigned_seat_no — which number a case was routed to.
--
-- nelos_roles is left in place, unread, with its data carried across, so
-- this is reversible. Anything defined there becomes a number in the order
-- the roles were listed.
--
-- Requires the four earlier nelos migrations.
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- Safe to re-run: every statement is guarded.
-- ============================================================================

-- ── PREFLIGHT ───────────────────────────────────────────────────
-- Stop with a sentence somebody can act on, rather than letting the first
-- ALTER fail with a bare 'relation does not exist'. Requires: the four earlier nelos migrations, in order.
DO $preflight$
BEGIN
  IF to_regclass('public.nelos_cases') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos migrations are out of order: "nelos_cases" does not exist yet.',
      HINT    = 'Run migration_nelos.sql first. The full order is: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql, migration_nelos_roles.sql, migration_nelos_seats.sql — or just run migration_nelos_all.sql, which is all five in one paste.';
  END IF;
  IF to_regclass('public.nelos_modules') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos migrations are out of order: "nelos_modules" does not exist yet.',
      HINT    = 'Run migration_nelos_modules.sql first. The full order is: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql, migration_nelos_roles.sql, migration_nelos_seats.sql — or just run migration_nelos_all.sql, which is all five in one paste.';
  END IF;
  IF to_regclass('public.nelos_handlers') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos migrations are out of order: "nelos_handlers" does not exist yet.',
      HINT    = 'Run migration_nelos_routing.sql first. The full order is: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql, migration_nelos_roles.sql, migration_nelos_seats.sql — or just run migration_nelos_all.sql, which is all five in one paste.';
  END IF;
  IF to_regclass('public.nelos_routes') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos migrations are out of order: "nelos_routes" does not exist yet.',
      HINT    = 'Run migration_nelos_roles.sql first. The full order is: migration_nelos.sql, migration_nelos_modules.sql, migration_nelos_routing.sql, migration_nelos_roles.sql, migration_nelos_seats.sql — or just run migration_nelos_all.sql, which is all five in one paste.';
  END IF;
END $preflight$;


-- ────────────────────────────────────────────────────────────────
-- PART 1: What one handler in a system is called
-- ────────────────────────────────────────────────────────────────
ALTER TABLE nelos_modules ADD COLUMN IF NOT EXISTS handler_label TEXT;

-- Singular, because it is always shown with a number after it. Only fills
-- blanks, so a label edited on the User Setting page survives a re-run.
UPDATE nelos_modules SET handler_label = v.lbl
  FROM (VALUES
    ('operation',   'Stock'),
    ('nursery_ops', 'Ops'),
    ('scan',        'FC'),
    ('mobile',      'Admin'),
    ('audit',       'Auditor')
  ) AS v(key, lbl)
 WHERE nelos_modules.key = v.key
   AND (nelos_modules.handler_label IS NULL OR nelos_modules.handler_label = '');

-- Any other section falls back to its own label, so a section added later
-- still reads as something rather than "undefined 1".
UPDATE nelos_modules SET handler_label = label
 WHERE handler_label IS NULL OR handler_label = '';

-- ────────────────────────────────────────────────────────────────
-- PART 2: A handler's number inside their system
-- ────────────────────────────────────────────────────────────────
ALTER TABLE nelos_handlers ADD COLUMN IF NOT EXISTS seat_no INT;

-- Two people cannot both be Admin 1 — every screen would be ambiguous.
-- Partial, so any number of handlers may sit unnumbered in a system.
CREATE UNIQUE INDEX IF NOT EXISTS nelos_handlers_seat_uniq
  ON nelos_handlers (primary_module, seat_no)
  WHERE primary_module IS NOT NULL AND seat_no IS NOT NULL;

ALTER TABLE nelos_routes ADD COLUMN IF NOT EXISTS to_seat_no INT;
ALTER TABLE nelos_cases  ADD COLUMN IF NOT EXISTS assigned_seat_no INT;

CREATE INDEX IF NOT EXISTS nelos_cases_seat_idx ON nelos_cases (assigned_seat_no);

-- ────────────────────────────────────────────────────────────────
-- PART 3: Carry nelos_roles across as numbers
--
-- Each system's roles become 1, 2, 3… in the order they were listed, and
-- everything pointing at a role follows. Guarded on to_regclass so a
-- database that never ran the roles migration skips the whole block.
-- ────────────────────────────────────────────────────────────────
DO $$
DECLARE n INT := 0;
BEGIN
  IF to_regclass('public.nelos_roles') IS NULL THEN
    RAISE NOTICE 'nelos_roles absent — nothing to carry across.';
    RETURN;
  END IF;

  CREATE TEMP TABLE _role_seat ON COMMIT DROP AS
    SELECT id AS role_id,
           module_key,
           row_number() OVER (PARTITION BY module_key ORDER BY sort_order, id) AS seat_no
      FROM public.nelos_roles;

  -- Handlers: only where they have no number yet, so a re-run cannot
  -- renumber somebody an admin has since moved.
  UPDATE public.nelos_handlers h
     SET seat_no = rs.seat_no
    FROM _role_seat rs
   WHERE h.role_id = rs.role_id
     AND h.seat_no IS NULL
     AND h.primary_module = rs.module_key;

  UPDATE public.nelos_routes r
     SET to_seat_no = rs.seat_no
    FROM _role_seat rs
   WHERE r.to_role_id = rs.role_id
     AND r.to_seat_no IS NULL;

  UPDATE public.nelos_cases c
     SET assigned_seat_no = rs.seat_no
    FROM _role_seat rs
   WHERE c.assigned_role_id = rs.role_id
     AND c.assigned_seat_no IS NULL;

  SELECT count(*) INTO n FROM _role_seat;
  RAISE NOTICE 'Carried % role(s) across as handler numbers.', n;
END $$;

-- Everybody pinned to a system but still unnumbered gets the next free
-- number, in the order they were set up. Without this a system that never
-- used roles would show a column of blanks the first time it is opened.
WITH numbered AS (
  SELECT h.id,
         COALESCE(
           (SELECT max(h2.seat_no) FROM nelos_handlers h2
             WHERE h2.primary_module = h.primary_module), 0)
         + row_number() OVER (PARTITION BY h.primary_module ORDER BY h.updated_at, h.id) AS n
    FROM nelos_handlers h
   WHERE h.primary_module IS NOT NULL
     AND h.seat_no IS NULL
)
UPDATE nelos_handlers h SET seat_no = numbered.n
  FROM numbered WHERE numbered.id = h.id;

-- ────────────────────────────────────────────────────────────────
-- PART 4: Routing, by number
-- ────────────────────────────────────────────────────────────────
-- ── Superseded by migration_nelos_hq.sql ────────────────────────
-- That file widens nelos_my_scope() with a sees_all column for HQ systems.
-- Re-running THIS file afterwards would drop the wider function and put the
-- narrower one back, silently switching HQ off — so when
-- nelos_modules.sees_all_cases exists, the later migration owns these
-- objects and this block stands down.
DO $guard$
BEGIN
IF EXISTS (SELECT 1 FROM information_schema.columns
            WHERE table_schema='public' AND table_name='nelos_modules'
              AND column_name='sees_all_cases') THEN
  RAISE NOTICE 'sees_all_cases present — migration_nelos_hq.sql owns nelos_my_scope(); leaving it as it is.';
  RETURN;
END IF;

EXECUTE $fn$
CREATE OR REPLACE FUNCTION public.nelos_route_case()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE r RECORD;
BEGIN
  -- An explicit destination wins: routing is the default, not a rule.
  IF NEW.assigned_module IS NOT NULL AND NEW.assigned_module <> '' THEN
    RETURN NEW;
  END IF;

  SELECT nr.to_module, nr.to_seat_no INTO r
    FROM nelos_routes nr
   WHERE nr.source_module = NEW.source_module
     AND (nr.category = NEW.category OR nr.category IS NULL)
   ORDER BY (nr.category IS NULL)          -- the exact category rule first
   LIMIT 1;

  IF FOUND THEN
    NEW.assigned_module := r.to_module;
    IF NEW.assigned_seat_no IS NULL THEN
      NEW.assigned_seat_no := r.to_seat_no;
    END IF;
  ELSE
    NEW.assigned_module := NEW.source_module;
  END IF;

  RETURN NEW;
END $$
$fn$;

EXECUTE $fn$
DROP TRIGGER IF EXISTS nelos_cases_route ON nelos_cases
$fn$;

EXECUTE $fn$
CREATE TRIGGER nelos_cases_route
  BEFORE INSERT ON nelos_cases
  FOR EACH ROW EXECUTE FUNCTION public.nelos_route_case()
$fn$;

EXECUTE $fn$
DROP FUNCTION IF EXISTS public.nelos_my_scope()
$fn$;

EXECUTE $fn$
DROP FUNCTION IF EXISTS public.nelos_people()
$fn$;

EXECUTE $fn$
CREATE FUNCTION public.nelos_my_scope()
RETURNS TABLE (primary_module TEXT, seat_no INT, categories TEXT[], is_admin BOOLEAN)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT h.primary_module,
         h.seat_no,
         h.categories,
         COALESCE(p.permissions->'modules'->>'nelos', 'none') = 'admin'
    FROM public.shared_profiles p
    LEFT JOIN public.nelos_handlers h ON h.user_id = p.id
   WHERE p.id = auth.uid()
$$
$fn$;

EXECUTE $fn$
GRANT EXECUTE ON FUNCTION public.nelos_my_scope() TO authenticated
$fn$;

EXECUTE $fn$
CREATE FUNCTION public.nelos_people()
RETURNS TABLE (
  id             UUID,
  full_name      TEXT,
  email          TEXT,
  nelos_level    TEXT,
  primary_module TEXT,
  seat_no        INT,
  categories     TEXT[]
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p.id,
         p.full_name,
         p.email,
         COALESCE(p.permissions->'modules'->>'nelos', 'none') AS nelos_level,
         h.primary_module,
         h.seat_no,
         h.categories
    FROM public.shared_profiles p
    LEFT JOIN public.nelos_handlers h ON h.user_id = p.id
   WHERE COALESCE(p.permissions->'modules'->>'nelos', 'none') <> 'none'
     AND EXISTS (
       SELECT 1 FROM public.shared_profiles me
        WHERE me.id = auth.uid()
          AND (COALESCE((me.permissions->>'manage_users')::boolean, false)
               OR COALESCE(me.permissions->'modules'->>'nelos', 'none') = 'admin')
     )
   ORDER BY COALESCE(NULLIF(p.full_name, ''), p.email)
$$
$fn$;

EXECUTE $fn$
GRANT EXECUTE ON FUNCTION public.nelos_people() TO authenticated
$fn$;
END $guard$;

-- ────────────────────────────────────────────────────────────────
-- PART 6: Check it landed
-- ────────────────────────────────────────────────────────────────
SELECT m.label AS system,
       m.handler_label || ' ' || h.seat_no AS role,
       COALESCE(NULLIF(h.full_name, ''), h.email) AS person
  FROM nelos_handlers h
  JOIN nelos_modules m ON m.key = h.primary_module
 ORDER BY m.sort_order, h.seat_no;

-- ── Rollback (manual, if ever needed) ───────────────────────────
--   ALTER TABLE nelos_cases    DROP COLUMN IF EXISTS assigned_seat_no;
--   ALTER TABLE nelos_routes   DROP COLUMN IF EXISTS to_seat_no;
--   ALTER TABLE nelos_handlers DROP COLUMN IF EXISTS seat_no;
--   ALTER TABLE nelos_modules  DROP COLUMN IF EXISTS handler_label;
--   then re-run migration_nelos_roles.sql to restore its trigger and the
--   role-shaped functions. nelos_roles and every *_role_id column were
--   never cleared, so the old behaviour comes back with them.

-- ############################################################################
-- ##  PART 6 of 9 — migration_nelos_hq.sql
-- ############################################################################

-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_nelos_hq.sql
--
-- NELOS — a system whose people see every case (HQ).
--
-- Nursery Operation is HQ: the people tagged there are not working one
-- queue, they are overseeing all of them. They need to see every case
-- raised anywhere, whichever system it was routed to.
--
-- That is a property of the SYSTEM, not of each person, so it is a flag on
-- nelos_modules rather than something to set on every handler. It is not
-- exposed as a toggle: HQ oversight is compulsory, not a preference. More
-- than one system may carry the flag if that is ever wanted — set it here.
--
-- WHAT IT CHANGES
--   Somebody tagged to an HQ system sees every case, exactly as an unpinned
--   person or a Nelos admin does. Everyone else is unaffected: their home
--   queue, plus anything with their name on it, minus anything routed to a
--   different number.
--
--   Routing is untouched. An HQ system can still be a routing destination
--   and still has its own queue; the flag only widens what its people SEE.
--
-- Requires the earlier nelos migrations — run migration_nelos_all.sql first.
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- Safe to re-run: every statement is guarded.
-- ============================================================================

-- ── PREFLIGHT ───────────────────────────────────────────────────
DO $preflight$
BEGIN
  IF to_regclass('public.nelos_modules') IS NULL
     OR to_regclass('public.nelos_handlers') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos tables do not exist yet.',
      HINT    = 'Run migration_nelos_all.sql first, then this file.';
  END IF;
END $preflight$;

-- ────────────────────────────────────────────────────────────────
-- PART 1: The flag
-- ────────────────────────────────────────────────────────────────
ALTER TABLE nelos_modules
  ADD COLUMN IF NOT EXISTS sees_all_cases BOOLEAN NOT NULL DEFAULT false;

-- Nursery Operation is HQ, and that is not a setting — there is no toggle
-- for it on the User Setting page, because HQ oversight is the whole reason
-- those people are in Nelos. So this is applied unconditionally rather than
-- only-if-nobody-else-has-it: with no UI to turn it back on, a system that
-- somehow lost the flag could never regain it.
UPDATE nelos_modules SET sees_all_cases = true
 WHERE key = 'nursery_ops' AND sees_all_cases IS DISTINCT FROM true;

-- ────────────────────────────────────────────────────────────────
-- PART 2: Scope carries it
--
-- The column is added to nelos_my_scope so the app asks one question and
-- gets the whole answer. CREATE OR REPLACE cannot widen a return type, so
-- the function is dropped first.
-- ────────────────────────────────────────────────────────────────
DROP FUNCTION IF EXISTS public.nelos_my_scope();

CREATE FUNCTION public.nelos_my_scope()
RETURNS TABLE (primary_module TEXT, seat_no INT, categories TEXT[],
               is_admin BOOLEAN, sees_all BOOLEAN)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT h.primary_module,
         h.seat_no,
         h.categories,
         COALESCE(p.permissions->'modules'->>'nelos', 'none') = 'admin',
         COALESCE(m.sees_all_cases, false)
    FROM public.shared_profiles p
    LEFT JOIN public.nelos_handlers h ON h.user_id = p.id
    LEFT JOIN public.nelos_modules  m ON m.key = h.primary_module
   WHERE p.id = auth.uid()
$$;

GRANT EXECUTE ON FUNCTION public.nelos_my_scope() TO authenticated;

-- ────────────────────────────────────────────────────────────────
-- PART 3: Check it landed
-- ────────────────────────────────────────────────────────────────
SELECT label AS system,
       CASE WHEN sees_all_cases THEN 'HQ — sees every case'
            ELSE 'sees its own queue' END AS visibility,
       (SELECT count(*) FROM nelos_handlers h WHERE h.primary_module = m.key) AS people
  FROM nelos_modules m
 ORDER BY sort_order;

-- ── Rollback (manual, if ever needed) ───────────────────────────
--   ALTER TABLE nelos_modules DROP COLUMN IF EXISTS sees_all_cases;
--   then re-run migration_nelos_seats.sql to restore the four-column
--   nelos_my_scope().

-- ############################################################################
-- ##  PART 7 of 9 — migration_nelos_category_system.sql
-- ############################################################################

-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_nelos_category_system.sql
--
-- NELOS — a case title belongs to one system.
--
-- Categories were global, so every system offered every one of them: the
-- Audit Portal listed a routing rule for "Planting Discrepancy" and the
-- Seedling Stock system listed one for "Height Shortfall". Combinations
-- nobody would ever file, on every screen.
--
-- A case title now belongs to the system it is raised in. Every title that
-- exists today goes to the Seedling Stock system, because that is where
-- they came from; the other systems start empty and get their own titles
-- as they are decided.
--
-- WHAT THIS CHANGES
--   • Case Routing lists only that system's own titles.
--   • The raise form offers only the titles of the system it is raised in.
--   • The Categories page groups by system and asks which one a new title
--     belongs to.
--
-- Routing is untouched: nelos_routes still stores the title by name, and a
-- case whose title has no rule still falls back the same way.
--
-- Requires the earlier nelos migrations — run migration_nelos_all.sql first.
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- Safe to re-run: every statement is guarded.
-- ============================================================================

-- ── PREFLIGHT ───────────────────────────────────────────────────
DO $preflight$
BEGIN
  IF to_regclass('public.nelos_categories') IS NULL
     OR to_regclass('public.nelos_modules') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos tables do not exist yet.',
      HINT    = 'Run migration_nelos_all.sql first, then this file.';
  END IF;
END $preflight$;

-- ────────────────────────────────────────────────────────────────
-- PART 1: Which system a title belongs to
-- ────────────────────────────────────────────────────────────────
ALTER TABLE nelos_categories
  ADD COLUMN IF NOT EXISTS module_key TEXT
    REFERENCES nelos_modules(key) ON UPDATE CASCADE ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS nelos_categories_module_idx
  ON nelos_categories (module_key, sort_order);

-- Everything that exists today came from the Seedling Stock system, so that
-- is where it goes. Only fills blanks: a title an admin has since moved to
-- another system stays where they put it.
UPDATE nelos_categories SET module_key = 'operation'
 WHERE module_key IS NULL;

-- A title is unique inside its system, not across the whole company —
-- "Pest / Disease" may reasonably exist under both Stock and Audit. The old
-- global UNIQUE on name would have refused that, so it is replaced.
DO $$
DECLARE c TEXT;
BEGIN
  SELECT conname INTO c
    FROM pg_constraint
   WHERE conrelid = 'public.nelos_categories'::regclass
     AND contype = 'u'
     AND pg_get_constraintdef(oid) ILIKE '%(name)%';
  IF c IS NOT NULL THEN
    EXECUTE format('ALTER TABLE nelos_categories DROP CONSTRAINT %I', c);
    RAISE NOTICE 'Dropped the global unique on nelos_categories.name.';
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS nelos_categories_uniq
  ON nelos_categories (module_key, lower(name));

-- ────────────────────────────────────────────────────────────────
-- PART 2: Check it landed
-- ────────────────────────────────────────────────────────────────
SELECT m.label AS system,
       COALESCE(string_agg(c.name, ', ' ORDER BY c.sort_order), '— none yet —') AS case_titles
  FROM nelos_modules m
  LEFT JOIN nelos_categories c ON c.module_key = m.key AND c.active
 GROUP BY m.label, m.sort_order
 ORDER BY m.sort_order;

-- ── Rollback (manual, if ever needed) ───────────────────────────
--   DROP INDEX IF EXISTS nelos_categories_uniq;
--   ALTER TABLE nelos_categories DROP COLUMN IF EXISTS module_key;
--   ALTER TABLE nelos_categories ADD CONSTRAINT nelos_categories_name_key UNIQUE (name);

-- ############################################################################
-- ##  PART 8 of 9 — migration_nelos_rls.sql
-- ############################################################################

-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_nelos_rls.sql
--
-- NELOS — close the row-level security holes.
--
-- WHY THIS EXISTS
--
-- Every nelos_* table shipped with the same two policies:
--
--     FOR SELECT TO authenticated USING (true)
--     FOR ALL    TO authenticated USING (true) WITH CHECK (true)
--
-- "authenticated" means ANY signed-in account, not any account with Nelos.
-- So today a Salesweb customer, an FC with only the scan module, anybody
-- who can log in at all, can open devtools and:
--
--   • read every case in the company, including ones deliberately scoped
--     away from them on the User Setting page,
--   • rewrite nelos_routes so every new case is routed to themselves,
--   • delete nelos_cases rows outright.
--
-- The app never offers any of that, which is exactly the point: the UI is
-- not a security boundary. The anon key is public by design and sits in
-- shared/shared_supabase.js, so anybody can call PostgREST directly.
-- RLS is the only thing standing between a signed-in account and the data,
-- and USING (true) is not standing anywhere.
--
-- WHAT THIS CHANGES
--
--   Config tables — nelos_modules, nelos_routes, nelos_roles,
--   nelos_categories, nelos_handlers:
--       read   any account holding Nelos
--       write  Nelos admins and portal user-managers only
--   These decide who sees what. A normal handler had no business
--   rewriting them and the app never asked to.
--
--   Work tables — nelos_cases, nelos_case_comments:
--       read   any account holding Nelos
--       write  any account holding Nelos      (raising, commenting,
--              claiming and resolving are everyone's job)
--       delete Nelos admins only              (a case is a record; the
--              way to retire one is to close it)
--
-- Reading is still deliberately not narrowed to a person's own scope. The
-- To-Do lists filter in the app, and pushing that into a policy would mean
-- a case moving queue could vanish from the raiser's own screen. What
-- matters here is that somebody with no Nelos at all now gets nothing.
--
-- Requires the nelos tables to exist — run migration_nelos_all.sql first.
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- Safe to re-run: policies are dropped and recreated by name.
-- ============================================================================

-- ── PREFLIGHT ───────────────────────────────────────────────────
DO $preflight$
BEGIN
  IF to_regclass('public.nelos_cases') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos tables do not exist yet.',
      HINT    = 'Run migration_nelos_all.sql first, then this file.';
  END IF;
END $preflight$;

-- ────────────────────────────────────────────────────────────────
-- PART 1: Two questions every policy asks
--
-- SECURITY DEFINER so the policy can read shared_profiles without the
-- caller needing to, and without recursing into that table's own policies.
-- ────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.nelos_has_access()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT COALESCE(p.permissions->'modules'->>'nelos', 'none') <> 'none'
       FROM public.shared_profiles p WHERE p.id = auth.uid()),
    false)
$$;

CREATE OR REPLACE FUNCTION public.nelos_is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT COALESCE(p.permissions->'modules'->>'nelos', 'none') = 'admin'
         OR COALESCE((p.permissions->>'manage_users')::boolean, false)
       FROM public.shared_profiles p WHERE p.id = auth.uid()),
    false)
$$;

GRANT EXECUTE ON FUNCTION public.nelos_has_access() TO authenticated;
GRANT EXECUTE ON FUNCTION public.nelos_is_admin()  TO authenticated;

-- ────────────────────────────────────────────────────────────────
-- PART 2: Replace the open policies
-- ────────────────────────────────────────────────────────────────
DO $$
DECLARE
  cfg  TEXT[] := ARRAY['nelos_modules','nelos_routes','nelos_roles',
                       'nelos_categories','nelos_handlers','nelos_module_members'];
  work TEXT[] := ARRAY['nelos_cases','nelos_case_comments'];
  t    TEXT;
  pol  RECORD;
BEGIN
  FOREACH t IN ARRAY cfg || work LOOP
    IF to_regclass('public.' || t) IS NULL THEN CONTINUE; END IF;

    -- Drop whatever is there by name, including the old open pair, so this
    -- is re-runnable and leaves exactly one set behind.
    FOR pol IN SELECT policyname FROM pg_policies
                WHERE schemaname = 'public' AND tablename = t
    LOOP
      EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', pol.policyname, t);
    END LOOP;

    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);

    -- Everyone holding Nelos may read.
    EXECUTE format($p$
      CREATE POLICY "nelos read" ON public.%I
        FOR SELECT TO authenticated
        USING (public.nelos_has_access())$p$, t);

    IF t = ANY(cfg) THEN
      -- Settings: admins only.
      EXECUTE format($p$
        CREATE POLICY "nelos admin write" ON public.%I
          FOR ALL TO authenticated
          USING (public.nelos_is_admin())
          WITH CHECK (public.nelos_is_admin())$p$, t);
    ELSE
      -- Casework: anybody with Nelos may add and change; only an admin
      -- may delete, so a case cannot be made to disappear.
      EXECUTE format($p$
        CREATE POLICY "nelos insert" ON public.%I
          FOR INSERT TO authenticated
          WITH CHECK (public.nelos_has_access())$p$, t);
      EXECUTE format($p$
        CREATE POLICY "nelos update" ON public.%I
          FOR UPDATE TO authenticated
          USING (public.nelos_has_access())
          WITH CHECK (public.nelos_has_access())$p$, t);
      EXECUTE format($p$
        CREATE POLICY "nelos delete" ON public.%I
          FOR DELETE TO authenticated
          USING (public.nelos_is_admin())$p$, t);
    END IF;

    RAISE NOTICE 'Locked down %', t;
  END LOOP;
END $$;

-- ────────────────────────────────────────────────────────────────
-- PART 3: Check it landed
-- ────────────────────────────────────────────────────────────────
SELECT tablename,
       string_agg(policyname || ' (' || cmd || ')', ', ' ORDER BY policyname) AS policies
  FROM pg_policies
 WHERE schemaname = 'public' AND tablename LIKE 'nelos%'
 GROUP BY tablename
 ORDER BY tablename;

-- ── Rollback (manual, if ever needed) ───────────────────────────
--   Re-running migration_nelos_all.sql does NOT restore the old open
--   policies, because its CREATE POLICY blocks are guarded on the policy
--   name and these are named differently. To go back, drop the policies
--   created above and recreate the pair by hand:
--     CREATE POLICY "Authenticated read <x>"  ON <t> FOR SELECT TO authenticated USING (true);
--     CREATE POLICY "Authenticated write <x>" ON <t> FOR ALL    TO authenticated USING (true) WITH CHECK (true);

-- ############################################################################
-- ##  PART 9 of 9 — migration_nelos_grant.sql
-- ############################################################################

-- ============================================================================
-- MJM AI POWERED SYSTEM — migration_nelos_grant.sql
--
-- NELOS — adding somebody from Pending Allocation grants them Nelos.
--
-- Until now, putting a person to work in Nelos took two screens: grant them
-- the module on the main portal's User Access, then come to Nelos and tag
-- them to a system. Anybody who did only the second half was tagged but
-- could not open the module, which reads on screen as "why can't they see
-- their cases".
--
-- The Pending Allocation section now searches everybody in the company by
-- name or email, and adding one of them does BOTH halves: it grants Nelos
-- on shared_profiles.permissions and creates their handler row.
--
-- WHY THIS NEEDS A FUNCTION
--   shared_profiles.permissions is writable only by somebody holding
--   manage_users (migration_access_and_reviews.sql). A Nelos admin who does
--   not also manage users could not make the grant. This function does it
--   on their behalf, and checks for itself that the caller is one or the
--   other before touching anything.
--
--   It grants 'normal', never 'admin', and never touches a person who
--   already has some level of Nelos — so it can only open the door, never
--   widen or narrow what somebody already has.
--
-- Requires the earlier nelos migrations — run migration_nelos_all.sql first.
-- Run in Supabase SQL Editor (main project: kibqjztozokohqmhqqqf).
-- Safe to re-run.
-- ============================================================================

-- ── PREFLIGHT ───────────────────────────────────────────────────
DO $preflight$
BEGIN
  IF to_regclass('public.nelos_handlers') IS NULL THEN
    RAISE EXCEPTION USING
      MESSAGE = 'Nelos tables do not exist yet.',
      HINT    = 'Run migration_nelos_all.sql first, then this file.';
  END IF;
END $preflight$;

-- ────────────────────────────────────────────────────────────────
-- Grant Nelos to one person.
--
-- Returns the level they hold afterwards, so the page can say what it did:
-- 'normal' when this call granted it, or whatever they already held.
-- ────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.nelos_grant_access(p_user_id UUID)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  current_level TEXT;
BEGIN
  -- Only a Nelos admin or a portal user-manager may open the door. Checked
  -- here rather than trusted from the page, because SECURITY DEFINER means
  -- this runs with rights the caller does not have.
  IF NOT EXISTS (
    SELECT 1 FROM public.shared_profiles me
     WHERE me.id = auth.uid()
       AND (COALESCE((me.permissions->>'manage_users')::boolean, false)
            OR COALESCE(me.permissions->'modules'->>'nelos', 'none') = 'admin')
  ) THEN
    RAISE EXCEPTION 'Only a Nelos admin may grant Nelos access.';
  END IF;

  SELECT COALESCE(permissions->'modules'->>'nelos', 'none')
    INTO current_level
    FROM public.shared_profiles
   WHERE id = p_user_id;

  IF current_level IS NULL THEN
    RAISE EXCEPTION 'No such user.';
  END IF;

  -- Already holds it at some level: leave it exactly as it is. This call
  -- opens a door, it does not decide how wide.
  IF current_level <> 'none' THEN
    RETURN current_level;
  END IF;

  UPDATE public.shared_profiles
     SET permissions = COALESCE(permissions, '{}'::jsonb)
         || jsonb_build_object('modules',
              COALESCE(permissions->'modules', '{}'::jsonb) || '{"nelos":"normal"}'::jsonb)
   WHERE id = p_user_id;

  RETURN 'normal';
END $$;

GRANT EXECUTE ON FUNCTION public.nelos_grant_access(UUID) TO authenticated;

-- ── Check it landed ─────────────────────────────────────────────
SELECT p.proname, pg_get_function_result(p.oid) AS returns
  FROM pg_proc p
 WHERE p.proname = 'nelos_grant_access';

-- ── Rollback (manual, if ever needed) ───────────────────────────
--   DROP FUNCTION IF EXISTS public.nelos_grant_access(UUID);
